test_case:
    case_descriptors:
        name: Test Case Name
        description: Test Case Description
    step_descriptors:
        description: Description
        expected_result: Expected Result

web:
    browser: firefox
    web_driver_wait_time: 60
    poll_time: 1
    implicit_wait_time: 60
    page_load_timeout: 30
    chrome_path: drivers/chromedriver.exe
    firefox_path: drivers/geckodriver.exe
    ie_path: drivers/IEDriverServer.exe
    edge_path: drivers/edge.exe
